### PR TITLE
Added Login Window & Function. Needs more estetik

### PR DESCRIPTION
**Pull request by Getting-into-coding**
Added:
- Added Home page
- The login button works. 
- The ID and Password input
- Disposes self (login page) and opens a new page for "Home Page"

Needed to be added/fixed:
- Need someone make the text, textfields, and buttons stay on the center of the screen.
- Needs better design
- Needs Icons, Logos, and Images
- The ID and password is hard-coded; need a better solution for this
- Homepage has nothing in it
- JLabels to indicate the text field if its ID or Password
- Needs an Implementation of message that says if ID or password is incorrect

This is what is looks like on my monitor (1366 x 768)
image

### CODE REVIEW

**Review by Nasamid — APPROVED** [review]
Maybe we need to add a forgot password button? Just to have a few more clickable stuff on the log in page.

**Comment by Getting-into-coding** [comment]
> Maybe we need to add a forgot password button? Just to have a few more clickable stuff on the log in page.
We can add it for looks for now, but i think we should implement its function later down the line once we have finished the other windows as well as the database

**Comment by AJBaterina** [comment]
.

**Comment by AJBaterina** [comment]
.

**Review by AJBaterina — APPROVED** [review]

**Pull request merged**
